export const ErrorCodes = {
  // Authentication
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Owners
  OWNER_NOT_FOUND: 'OWNER_NOT_FOUND',
  OWNER_PHONE_CONFLICT: 'OWNER_PHONE_CONFLICT',

  // Dogs
  DOG_NOT_FOUND: 'DOG_NOT_FOUND',
  DOG_ARCHIVED: 'DOG_ARCHIVED',
  INVALID_AVATAR: 'INVALID_AVATAR',

  // Bookings
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_OVERLAP: 'BOOKING_OVERLAP',
  BOOKING_INVALID_TIME_RANGE: 'BOOKING_INVALID_TIME_RANGE',
  BOOKING_ARCHIVED_DOG_BLOCKED: 'BOOKING_ARCHIVED_DOG_BLOCKED',

  // Statuses
  INVALID_STATUS: 'INVALID_STATUS',
  STATUS_CHANGE_REQUIRES_DATE: 'STATUS_CHANGE_REQUIRES_DATE',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  BACKUP_FAILED: 'BACKUP_FAILED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
